prepare-sources:: sources-internal checkout-release

# Appended for releasing $(cat RELEASE_COMMIT)
sources-internal: Makefile.internal
	make -f Makefile.internal sources

checkout-release: Makefile.internal
	make -f Makefile.internal $@

